# Site settings
title: Ilya Paskhover's blog/projects
description: > # this means to ignore newlines until "baseurl:"
  This is an awesome description from _config.yml file.
  It will appear in my document head meta (for
  Google search results) and in my feed.xml site description (if I'll add it).
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://ilya-paskhover.github.io" # the base hostname & protocol for your site
github_username:  ilya-paskhover

# Build settings
markdown: kramdown

host: 0.0.0.0
port: 4000

